### ISSUE TITLE
macros: Any macro in the return position will result in Rust GCC stuck

### ISSUE THREAD

**Issue by liushuyu** [Rust-GCC/gccrs#1084]
I tried this code:

```rust
macro_rules! add {
    ($a:expr) => { $a };
    ($a:expr, $($b:expr),+) => { $a + add!($($b),*) }
}

fn test() -> i32 {
    add!(add!(1, 2), add!(1, 2))
}

fn main() {
    let _ = test();
}
```

A reduced case for `gccrs`:

```rust
macro_rules! add {
    ($a:expr) => { $a };
    ($a:expr, $($b:expr),+) => { $a + add!($($b),*) }
}

fn main() -> i32 {
    add!(add!(1, 2))
}
```

I expected to see this happen: `gccrs` should compile the code, and the generated program should run and exit with `6` (the reduced case should exit with `3`).

Instead, this happened: `gccrs` stuck in an infinite loop in the macro expansion pass.

### Stack Trace

<details>
<summary>Click to show detailed stack trace</summary>
<p>

```
#0  0x00007ffff79cf4c4 in __memmove_avx_unaligned_erms () from /usr/lib/libc.so.6
#1  0x00000000020f5731 in std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) ()
#2  0x00000000020e5f54 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) ()
#3  0x0000000000934a03 in std::operator<< <std::char_traits<char> > (__c=<optimized out>, __out=...) at /usr/include/c++/11.2.0/ostream:518
#4  expand_format (fmt=<optimized out>) at ../../gcc/rust/rust-diagnostics.cc:42
#5  expand_message(const char *, typedef __va_list_tag __va_list_tag *) (fmt=<optimized out>, ap=0x7fffffffc788) at ../../gcc/rust/rust-diagnostics.cc:114
#6  0x00000000009353b2 in Rust::Error::Error (this=this@entry=0x7fffffffc960, location=..., fmt=fmt@entry=0x2139080 "unrecognised token %qs for start of %s")
    at ../../gcc/rust/rust-diagnostics.cc:239
#7  0x0000000000a50d65 in Rust::Parser<Rust::MacroInvocLexer>::parse_item (this=0x7fffffffcb80, called_from_statement=called_from_statement@entry=true)
    at ../../gcc/rust/parse/rust-parse-impl.h:1095
#8  0x0000000000a059b9 in operator() (__closure=<optimized out>, __closure=<optimized out>) at ../../gcc/rust/expand/rust-macro-expand.cc:811
#9  std::__invoke_impl<Rust::AST::SingleASTNode, Rust::transcribe_many_items(Rust::Parser<Rust::MacroInvocLexer>&, Rust::TokenId&)::<lambda()>&> (__f=...)
    at /usr/include/c++/11.2.0/bits/invoke.h:61
#10 std::__invoke_r<Rust::AST::SingleASTNode, Rust::transcribe_many_items(Rust::Parser<Rust::MacroInvocLexer>&, Rust::TokenId&)::<lambda()>&> (__fn=...)
    at /usr/include/c++/11.2.0/bits/invoke.h:143
#11 std::_Function_handler<Rust::AST::SingleASTNode(), Rust::transcribe_many_items(Rust::Parser<Rust::MacroInvocLexer>&, Rust::TokenId&)::<lambda()> >::_M_invoke(const std::_Any_data &) (
    __functor=...) at /usr/include/c++/11.2.0/bits/std_function.h:292
#12 0x00000000009fbed4 in std::function<Rust::AST::SingleASTNode ()>::operator()() const (this=0x7fffffffcc10) at /usr/include/c++/11.2.0/bits/std_function.h:560
#13 Rust::parse_many(Rust::Parser<Rust::MacroInvocLexer> &, Rust::TokenId &, std::function<Rust::AST::SingleASTNode()>) (parser=..., delimiter=@0x7fffffffcab0: Rust::RIGHT_CURLY, 
    parse_fn=...) at ../../gcc/rust/expand/rust-macro-expand.cc:794
#14 0x0000000000a041f3 in Rust::transcribe_many_stmts (delimiter=<optimized out>, parser=...) at ../../gcc/rust/expand/rust-macro-expand.cc:896
#15 Rust::transcribe_on_delimiter (last_token_id=<optimized out>, delimiter=<optimized out>, semicolon=<optimized out>, parser=...) at ../../gcc/rust/expand/rust-macro-expand.cc:930
#16 Rust::transcribe_context (last_token_id=<optimized out>, delimiter=<optimized out>, semicolon=false, parser=..., ctx=Rust::MacroExpander::ITEM)
    at ../../gcc/rust/expand/rust-macro-expand.cc:978
#17 Rust::MacroExpander::transcribe_rule (this=<optimized out>, match_rule=..., invoc_token_tree=..., matched_fragments=..., semicolon=<optimized out>, ctx=Rust::MacroExpander::ITEM)
    at ../../gcc/rust/expand/rust-macro-expand.cc:1054
#18 0x0000000000a07573 in Rust::MacroExpander::expand_decl_macro (this=0x7fffffffd100, invoc_locus=..., invoc=..., rules_def=..., semicolon=<optimized out>)
    at ../../gcc/rust/expand/rust-macro-expand.cc:149
#19 0x0000000000a078db in Rust::MacroExpander::expand_invoc (this=0x7fffffffd100, invoc=...) at ../../gcc/rust/expand/rust-macro-expand.cc:205
#20 0x0000000000a56b75 in Rust::AttrVisitor::visit (this=0x7fffffffcfe0, expr=...) at ../../gcc/rust/expand/rust-attribute-visitor.cc:622
#21 0x00000000009fc43f in Rust::MacroExpander::take_expanded_fragment (vis=..., this=0x7fffffffd100) at ../../gcc/rust/expand/rust-macro-expand.h:303
#22 Rust::MacroExpander::expand_crate (this=this@entry=0x7fffffffd100) at ../../gcc/rust/expand/rust-macro-expand.cc:382
#23 0x00000000009dc376 in Rust::Session::expansion (this=this@entry=0x2bf56c0 <Rust::Session::get_instance()::instance>, crate=...) at ../../gcc/rust/rust-session-manager.cc:831
#24 0x00000000009e888a in Rust::Session::parse_file (this=this@entry=0x2bf56c0 <Rust::Session::get_instance()::instance>, filename=<optimized out>)
    at ../../gcc/rust/rust-session-manager.cc:568
#25 0x00000000009e8e31 in Rust::Session::parse_files (this=0x2bf56c0 <Rust::Session::get_instance()::instance>, num_files=1, files=<optimized out>)
    at ../../gcc/rust/rust-session-manager.cc:484
#26 0x00000000010a0dc1 in compile_file () at ../../gcc/toplev.cc:452
#27 0x000000000092c96e in do_compile (no_backend=false) at ../../gcc/toplev.cc:2158
#28 toplev::main (this=this@entry=0x7fffffffd876, argc=<optimized out>, argc@entry=6, argv=<optimized out>, argv@entry=0x7fffffffd9a8) at ../../gcc/toplev.cc:2310
#29 0x000000000092e8ec in main (argc=6, argv=0x7fffffffd9a8) at ../../gcc/main.cc:39
```
</p>
</details>

### Meta

- Rust GCC version: 9011184f38a04f81ba3194b826bec3f30a11c07b

**Comment by liushuyu** [comment]
I just went through some of the issues, and I found this issue is awfully similar to #1048. Probably fixing one of them will fix the other?
