### ISSUE TITLE
Remark CI complains about JavaScript syntax

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#1340]
Output from the CI. Unless the javascript spec changed overnight I don't understand how this could have happened. @mvvsmk if you have any ideas feel free :)

```
> Run git ls-files -z *.md | xargs -0 -n 1 npx remark -u lint -f > /dev/null
/home/runner/work/gccrs/gccrs/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/gccrs/gccrs/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
/home/runner/work/gccrs/gccrs/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/gccrs/gccrs/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
/home/runner/work/gccrs/gccrs/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/gccrs/gccrs/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Error: Process completed with exit code 123.
```

**Comment by CohenArthur** [comment]
Disabled it for now in #1341

**Comment by mvvsmk** [comment]
@CohenArthur , I wanted to see if I could replicate the bug on my end, but I couldn't, as you can see here.
```
gccrs on  master took 15s 
❯ npm install remark-cli remark-lint remark-lint-maximum-line-length remark-preset-lint-recommended remark-gfm

added 200 packages, and audited 201 packages in 15s

110 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

gccrs on  master [?] via  v18.3.0 took 15s 
❯ git ls-files -z *.md | xargs -0 -n 1 npx remark -u lint -f > /dev/null
CODE_OF_CONDUCT.md: no issues found
CONTRIBUTING.md: no issues found
README.md: no issues found

gccrs on  master [?] via  v18.3.0 took 2s 
❯ 
```
The only difference between what I ran was I was using node version 18, whereas the git hub actions script uses node version '12.X'. Not that it should pose any problem considering it worked for the last 930 times. 

This is the repo for the remark-linter I used [[here]](https://github.com/remarkjs/remark-lint)
For reference this is another instance of the same linter used for rust-lang/rust-clippy [[here]](https://github.com/rust-lang/rust-clippy/blob/master/.github/workflows/remark.yml)
The tiny difference is they use node 14 but I don't know what went wrong suddenly in node 12 while it was working correctly till now.
