### ISSUE TITLE
ICE with Rustc testcase method-normalize-bounds-issue-20604.rs

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#1524]
### Code

Trying rustc test case https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/src/test/ui/methods/method-normalize-bounds-issue-20604.rs

```rust
// run-pass
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(stable_features)]

// Test that we handle projection types which wind up important for
// resolving methods. This test was reduced from a larger example; the
// call to `foo()` at the end was failing to resolve because the
// winnowing stage of method resolution failed to handle an associated
// type projection.

// pretty-expanded FIXME #23616

#![feature(associated_types)]

trait Hasher {
    type Output;
    fn finish(&self) -> Self::Output;
}

trait Hash<H: Hasher> {
    fn hash(&self, h: &mut H);
}

trait HashState {
    type Wut: Hasher;
    fn hasher(&self) -> Self::Wut;
}

struct SipHasher;
impl Hasher for SipHasher {
    type Output = u64;
    fn finish(&self) -> u64 { 4 }
}

impl Hash<SipHasher> for isize {
    fn hash(&self, h: &mut SipHasher) {}
}

struct SipState;
impl HashState for SipState {
    type Wut = SipHasher;
    fn hasher(&self) -> SipHasher { SipHasher }
}

struct Map<S> {
    s: S,
}

impl<S> Map<S>
    where S: HashState,
          <S as HashState>::Wut: Hasher<Output=u64>,
{
    fn foo<K>(&self, k: K) where K: Hash< <S as HashState>::Wut> {}
}

fn foo<K: Hash<SipHasher>>(map: &Map<SipState>) {
    map.foo(22);
}

fn main() {}

```

see: https://godbolt.org/z/Mx4MabzvT

### Meta

- What version of Rust GCC were you using, git sha if possible. 4f0a2729d78d77f14140531ca809d1c45311f0c9

### Error output

```
rust1: internal compiler error: Segmentation fault
```

<details><summary>Backtrace</summary>
  <p>
  
  ```
 rust1: internal compiler error: Segmentation fault
0x228353e internal_error(char const*, ...)
	???:0
0xc6cd4c Rust::Resolver::ResolveRelativeQualTypePath::go(Rust::AST::QualifiedPathInType&)
	???:0
0xc6cee1 Rust::Resolver::ResolveGenericArgs::resolve_disambiguated_generic(Rust::AST::GenericArg&)
	???:0
0xc6d9ce Rust::Resolver::ResolveGenericArgs::go(Rust::AST::GenericArgs&, Rust::Resolver::CanonicalPath const&, Rust::Resolver::CanonicalPath const&)
	???:0
0xc6da56 Rust::Resolver::ResolveGenericArgs::go(Rust::AST::GenericArgs&)
	???:0
0xc6e2ce Rust::Resolver::ResolveRelativeTypePath::go(Rust::AST::TypePath&, unsigned int&)
	???:0
0xc67f5e Rust::Resolver::ResolveTypeBound::visit(Rust::AST::TraitBound&)
	???:0
0xc68047 Rust::Resolver::ResolveWhereClause::visit(Rust::AST::TypeBoundWhereClauseItem&)
	???:0
0xc686df Rust::Resolver::ResolveWhereClause::Resolve(Rust::AST::WhereClause&)
	???:0
0xc651ea Rust::Resolver::ResolveItem::visit(Rust::AST::Method&)
	???:0
0xc5d651 Rust::Resolver::ResolveImplItems::go(Rust::AST::InherentImplItem*, Rust::Resolver::CanonicalPath const&, Rust::Resolver::CanonicalPath const&)
	???:0
0xc660a8 Rust::Resolver::ResolveItem::visit(Rust::AST::InherentImpl&)
	???:0
0xc5d567 Rust::Resolver::ResolveItem::go(Rust::AST::Item*, Rust::Resolver::CanonicalPath const&, Rust::Resolver::CanonicalPath const&)
	???:0
0xc4d853 Rust::Resolver::NameResolution::go(Rust::AST::Crate&)
	???:0
0xb5c8a1 Rust::Session::compile_crate(char const*)
	???:0
0xb5d2ab Rust::Session::handle_input_files(int, char const**)
	???:0
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
Compiler returned: 1
  ```
  
  </p>
</details>

**Comment by philberty** [comment]
I am pretty sure the issue will be:

```
impl<S> Map<S>
    where S: HashState,
          <S as HashState>::Wut: Hasher<Output=u64>,
```

Assigning the associated type like this is something that isn't implemented yet

**Comment by philberty** [comment]
backtrace with debug info:

```
Program received signal SIGSEGV, Segmentation fault.
Rust::Resolver::ResolveRelativeQualTypePath::go (path=...) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve-type.cc:286
286       associated->accept_vis (o);
(gdb) 
(gdb) bt
#0  Rust::Resolver::ResolveRelativeQualTypePath::go (path=...) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve-type.cc:286
#1  0x00000000013072d6 in Rust::Resolver::ResolveType::visit (this=0x7fffffffcaf0, path=...) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve-type.h:95
#2  0x0000000001086a2a in Rust::AST::QualifiedPathInType::accept_vis (this=0x4877d50, vis=...) at ../../gccrs/gcc/rust/ast/rust-ast-full-test.cc:4946
#3  0x00000000012fe455 in Rust::Resolver::ResolveType::go (type=0x4877d50) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve-type.h:63
#4  0x0000000001306bdb in Rust::Resolver::ResolveGenericArgs::resolve_disambiguated_generic (this=0x7fffffffcbb0, arg=...) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve-type.cc:551
#5  0x0000000001306d1c in Rust::Resolver::ResolveGenericArgs::go (generic_args=..., prefix=..., canonical_prefix=...) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve-type.cc:577
#6  0x0000000001306c3e in Rust::Resolver::ResolveGenericArgs::go (generic_args=...) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve-type.cc:562
#7  0x0000000001305251 in Rust::Resolver::ResolveRelativeTypePath::go (path=..., resolved_node_id=@0x7fffffffcd88: 0) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve-type.cc:143
#8  0x00000000013072b3 in Rust::Resolver::ResolveType::visit (this=0x7fffffffcd70, path=...) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve-type.h:90
#9  0x00000000010869b4 in Rust::AST::TypePath::accept_vis (this=0x4877ea8, vis=...) at ../../gccrs/gcc/rust/ast/rust-ast-full-test.cc:4934
#10 0x00000000012fe455 in Rust::Resolver::ResolveType::go (type=0x4877ea8) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve-type.h:63
#11 0x00000000012fe548 in Rust::Resolver::ResolveTypeBound::visit (this=0x7fffffffce10, bound=...) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve-type.h:132
#12 0x00000000010884e6 in Rust::AST::TraitBound::accept_vis (this=0x4877e80, vis=...) at ../../gccrs/gcc/rust/ast/rust-ast-full-test.cc:5666
#13 0x00000000012fe4f5 in Rust::Resolver::ResolveTypeBound::go (type=0x4877e80) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve-type.h:126
#14 0x00000000012feaef in Rust::Resolver::ResolveWhereClause::visit (this=0x7fffffffcf00, item=...) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve-type.h:221
#15 0x000000000108777c in Rust::AST::TypeBoundWhereClauseItem::accept_vis (this=0x4876af0, vis=...) at ../../gccrs/gcc/rust/ast/rust-ast-full-test.cc:5312
#16 0x00000000012fea04 in Rust::Resolver::ResolveWhereClause::Resolve (where_clause=...) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve-type.h:211
#17 0x00000000012f8ea8 in Rust::Resolver::ResolveItem::visit (this=0x7fffffffd140, method=...) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve-item.cc:614
#18 0x00000000010877b4 in Rust::AST::Method::accept_vis (this=0x4877ef0, vis=...) at ../../gccrs/gcc/rust/ast/rust-ast-full-test.cc:5318
#19 0x00000000012fab0d in Rust::Resolver::ResolveImplItems::go (item=0x4877ef0, prefix=..., canonical_prefix=...) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve-item.cc:988
#20 0x00000000012fa38d in Rust::Resolver::ResolveItem::resolve_impl_item (this=0x7fffffffd3a0, item=0x4877ef0, prefix=..., canonical_prefix=...) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve-item.cc:839
#21 0x00000000012f8a38 in Rust::Resolver::ResolveItem::visit (this=0x7fffffffd3a0, impl_block=...) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve-item.cc:578
#22 0x0000000001087d30 in Rust::AST::InherentImpl::accept_vis (this=0x4878170, vis=...) at ../../gccrs/gcc/rust/ast/rust-ast-full-test.cc:5462
#23 0x00000000012f5f6e in Rust::Resolver::ResolveItem::go (item=0x4878170, prefix=..., canonical_prefix=...) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve-item.cc:188
#24 0x00000000012e8c79 in Rust::Resolver::NameResolution::go (this=0x487f3d0, crate=...) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve.cc:108
#25 0x00000000012e8892 in Rust::Resolver::NameResolution::Resolve (crate=...) at ../../gccrs/gcc/rust/resolve/rust-ast-resolve.cc:58
#26 0x000000000118081f in Rust::Session::compile_crate (this=0x4646180 <Rust::Session::get_instance()::instance>, filename=0x7fffffffe070 "test.rs") at ../../gccrs/gcc/rust/rust-session-manager.cc:518
#27 0x000000000117fee9 in Rust::Session::handle_input_files (this=0x4646180 <Rust::Session::get_instance()::instance>, num_files=1, files=0x4858d00) at ../../gccrs/gcc/rust/rust-session-manager.cc:363
#28 0x00000000010300e8 in grs_langhook_parse_file () at ../../gccrs/gcc/rust/rust-lang.cc:180
#29 0x0000000001c1097a in compile_file () at ../../gccrs/gcc/toplev.cc:452
#30 0x0000000001c13b1d in do_compile (no_backend=false) at ../../gccrs/gcc/toplev.cc:2146
#31 0x0000000001c13f19 in toplev::main (this=0x7fffffffdaf2, argc=10, argv=0x7fffffffdc28) at ../../gccrs/gcc/toplev.cc:2298
#32 0x0000000003509d4b in main (argc=10, argv=0x7fffffffdc28) at ../../gccrs/gcc/main.cc:39
```
